export enum ModelName {
  ROLE = "_Role",
  ACCOUNT = "_Account",
  SALARY = "Salary",
  BASIC_SALARY = "BasicSalary",
  ALLOWANCE_SALARY = "AllowanceSalary",
  OVERTIME_SALARY = "OvertimeSalary",
  LOAN_SALARY = "LoanSalary",
  DEDUCTION_SALARY = "DeductionSalary",
  OTHER_SALARY = "OtherSalary",
  POSITION = "Position",
  DEPARTMENT = "Department",
  AREA = "Area",
  BRANCH = "Branch",
  EMPLOYEE = "Employee",
}
