export enum FilterTypeEnum {
  TIME_SHEET = "TIME_SHEET",
  PAYROLL = "PAYROLL",
  SEASONAL = "SEASONAL",
  BASIC = "BASIC",
  STAY = "STAY",
  PERMANENT = "PERMANENT",
  OVERTIME = "OVERTIME",
  ALLOWANCE = "ALLOWANCE",
  ABSENT = "ABSENT",
  REMOTE = "REMOTE",
}
