// import { LANGUAGE } from "src/api/language/constants"

export const DEFAULT_CONSTANTS = {
  // LANGUAGE: LANGUAGE.EN,
  DEFAULT_LIMIT_PER_PAGE_LOAD: 18,
  DEFAULT_LIMIT_IMAGES_PER_PAGE_LOAD: 18,
  DEFAULT_LIMIT_NEWS_FEED_PER_PAGE_LOAD: 10,
  DEFAULT_LIMIT_DANCES_IN_NEWS_FEED: 3,
  DEFAULT_LIMIT_FAVORITES_IN_NEWS_FEED: 3,
  DEFAULT_LIMIT_MESSAGES_PER_PAGE_LOAD: 10,
  DEFAULT_LIMIT_CONTACTS_PER_PAGE_LOAD: 20,
  DEFAULT_LIMIT_INVITATIONS_PER_PAGE_LOAD: 20,
  DEFAULT_LIMIT_CONVERSATIONS_PER_PAGE_LOAD: 20,

  DEFAULT_LIMIT_GET_USERS_IN_ADMIN: 10,
  DEFAULT_LIMIT_GET_TRANSLATIONS_IN_ADMIN: 10,
  DEFAULT_LIMIT_GET_CATEGORIES_IN_ADMIN: 10,

  DEFAULT_ANALYTICS_EVENTS_SENT_PER_TEN_SECONDS: 500,
  DEFAULT_API_REQUESTS_AMPLITUDE_EVENTS_SENT: 100,
  DEFAULT_AMPLITUDE_EVENTS_PER_BATCHES: 10,
  DEFAULT_TIME_TOKEN_EXPIRES: 86400000, // 24 hours

  DEFAULT_LIMIT_CATEGORIES_PER_PAGE_LOAD: 3,
  DEFAULT_LIMIT_ITEMS_PER_CATEGORY: 6,

  DEFAULT_RADIUS: 50000, // 50 KM

  DEFAULT_PAYMENT_PERIOD_DAYS: 30, // 30 days

  DEFAULT_LIMIT_USERS_PER_PAGE_LOAD: 10,
  DEFAULT_LIMIT_CITIES_PER_PAGE_LOAD: 5,

  DEFAULT_LIMIT_GET_PLACES_BY_CATEGORY: 10,
  DEFAULT_LIMIT_GET_ORDERS: 10,
  DEFAULT_LIMIT_GET_CATEGORIES: 1000,
  DEFAULT_LIMIT_GET_SUB_CATEGORIES: 1000,
  DEFAULT_MARGIN_OF_CIRCLE: 10, // meter

  DEFAULT_LIMIT_GET_PRODUCTS: 200,
  DEFAULT_LIMIT_GET_SERVICES: 200
};
